name: Tarantool key-value server deploy
on:
  push:
    branches:
      - master
jobs:
  CD:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build
        run: |
          docker build -t rflban/interview_tarantool-kv .
          docker push rflban/interview_tarantool-kv


      - name: run
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_SERVER_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull rflban/interview_tarantool-kv
            docker run -d -p 8080:8080 rflban/interview_tarantool-kv
